.TH "ESYS_TR_defines" 3 "Sun May 7 2023" "Version 4.0.1" "tpm2-tss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ESYS_TR_defines \- Global ESYS_TR objects
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
A set of defines for global virtual objects that are always present in every \fBESYS_CONTEXT\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for tpm2-tss from the source code\&.
