'\" t
.\"     Title: glib-mkenums
.\"    Author: Owen Taylor
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/23/2023
.\"    Manual: User Commands
.\"    Source: GObject
.\"  Language: English
.\"
.TH "GLIB\-MKENUMS" "1" "" "GObject" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
glib-mkenums \- C language enum description generation utility
.SH "SYNOPSIS"
.HP \w'\fBglib\-mkenums\fR\ 'u
\fBglib\-mkenums\fR [OPTION...] [FILE...]
.SH "DESCRIPTION"
.PP
\fBglib\-mkenums\fR
is a small utility that parses C code to extract enum definitions and produces enum descriptions based on text templates specified by the user\&. Typically, you can use this tool to generate enumeration types for the GType type system, for GObject properties and signal marshalling; additionally, you can use it to generate enumeration values of GSettings schemas\&.
.PP
\fBglib\-mkenums\fR
takes a list of valid C code files as input\&. The options specified control the text that generated, substituting various keywords enclosed in
@
characters in the templates\&.
.PP
Since version 2\&.74, GLib provides the
G_DEFINE_ENUM_TYPE
and
G_DEFINE_FLAGS_TYPE
C pre\-processor macros\&. These macros can be used to define a GType for projects that have few, small enumeration types without going through the complexities of generating code at build time\&.
.SS "Production text substitutions"
.PP
Certain keywords enclosed in
@
characters will be substituted in the emitted text\&. For the substitution examples of the keywords below, the following example enum definition is assumed:
.sp
.if n \{\
.RS 4
.\}
.nf
typedef enum
{
  PREFIX_THE_XVALUE    = 1 << 3,
  PREFIX_ANOTHER_VALUE = 1 << 4
} PrefixTheXEnum;
.fi
.if n \{\
.RE
.\}
.PP
@EnumName@
.RS 4
The name of the enum currently being processed, enum names are assumed to be properly namespaced and to use mixed capitalization to separate words (e\&.g\&.
PrefixTheXEnum)\&.
.RE
.PP
@enum_name@
.RS 4
The enum name with words lowercase and word\-separated by underscores (e\&.g\&.
prefix_the_xenum)\&.
.RE
.PP
@ENUMNAME@
.RS 4
The enum name with words uppercase and word\-separated by underscores (e\&.g\&.
PREFIX_THE_XENUM)\&.
.RE
.PP
@ENUMSHORT@
.RS 4
The enum name with words uppercase and word\-separated by underscores, prefix stripped (e\&.g\&.
THE_XENUM)\&.
.RE
.PP
@ENUMPREFIX@
.RS 4
The prefix of the enum name (e\&.g\&.
PREFIX)\&.
.RE
.PP
@VALUENAME@
.RS 4
The enum value name currently being processed with words uppercase and word\-separated by underscores, this is the assumed literal notation of enum values in the C sources (e\&.g\&.
PREFIX_THE_XVALUE)\&.
.RE
.PP
@valuenick@
.RS 4
A nick name for the enum value currently being processed, this is usually generated by stripping common prefix words of all the enum values of the current enum, the words are lowercase and underscores are substituted by a minus (e\&.g\&.
the\-xvalue)\&.
.RE
.PP
@valuenum@
.RS 4
The integer value for the enum value currently being processed\&. If the evaluation fails then
\fBglib\-mkenums\fR
will exit with an error status, but this only happens if
@valuenum@
appears in your value production template\&. (Since: 2\&.26)
.RE
.PP
@type@
.RS 4
This is substituted either by "enum" or "flags", depending on whether the enum value definitions contained bit\-shift operators or not (e\&.g\&.
flags)\&.
.RE
.PP
@Type@
.RS 4
The same as
@type@
with the first letter capitalized (e\&.g\&.
Flags)\&.
.RE
.PP
@TYPE@
.RS 4
The same as
@type@
with all letters uppercased (e\&.g\&.
FLAGS)\&.
.RE
.PP
@filename@
.RS 4
The full path of the input file currently being processed (e\&.g\&.
/build/environment/project/src/foo\&.h)\&.
.RE
.PP
@basename@
.RS 4
The base name of the input file currently being processed (e\&.g\&.
foo\&.h)\&. Typically you want to use
@basename@
in place of
@filename@
in your templates, to improve the reproducibility of the build\&. (Since: 2\&.22)
.RE
.SS "Trigraph extensions"
.PP
Some C comments are treated specially in the parsed enum definitions, such comments start out with the trigraph sequence
/*<
and end with the trigraph sequence
>*/\&.
.PP
The following options can be specified per enum definition:
.PP
skip
.RS 4
Indicates this enum definition should be skipped\&.
.RE
.PP
flags
.RS 4
Indicates this enum should be treated as a flags definition\&.
.RE
.PP
underscore_name
.RS 4
Specifies the word separation used in the
\fB*_get_type()\fR
function\&. For instance,
/*< underscore_name=gnome_vfs_uri_hide_options >*/\&.
.RE
.PP
since
.RS 4
Specifies the version tag that will be used to substitute the
@enumsince@
keyword in the template, useful when documenting methods generated from the enums (e\&.g\&.
Since: @enumsince@)\&. (Since: 2\&.66)
.RE
.PP
The following options can be specified per value definition:
.PP
skip
.RS 4
Indicates the value should be skipped\&.
.RE
.PP
nick
.RS 4
Specifies the otherwise auto\-generated nickname\&.
.RE
.PP
Examples:
.sp
.if n \{\
.RS 4
.\}
.nf
typedef enum /*< skip >*/
{
  PREFIX_FOO
} PrefixThisEnumWillBeSkipped;
typedef enum /*< flags,prefix=PREFIX,since=1\&.0 >*/
{
  PREFIX_THE_ZEROTH_VALUE,	/*< skip >*/
  PREFIX_THE_FIRST_VALUE,
  PREFIX_THE_SECOND_VALUE,
  PREFIX_THE_THIRD_VALUE,	/*< nick=the\-last\-value >*/
} PrefixTheFlagsEnum;
.fi
.if n \{\
.RE
.\}
.SH "OPTIONS"
.PP
\fB\-\-fhead\fR \fITEXT\fR
.RS 4
Emits
\fITEXT\fR
prior to processing input files\&.
.sp
You can specify this option multiple times, and the
\fITEXT\fR
will be concatenated\&.
.sp
When used along with a template file,
\fITEXT\fR
will be prepended to the template\*(Aqs
file\-header
section\&.
.RE
.PP
\fB\-\-fprod\fR \fITEXT\fR
.RS 4
Emits
\fITEXT\fR
every time a new input file is being processed\&.
.sp
You can specify this option multiple times, and the
\fITEXT\fR
will be concatenated\&.
.sp
When used along with a template file,
\fITEXT\fR
will be appended to the template\*(Aqs
file\-production
section\&.
.RE
.PP
\fB\-\-ftail\fR \fITEXT\fR
.RS 4
Emits
\fITEXT\fR
after all input files have been processed\&.
.sp
You can specify this option multiple times, and the
\fITEXT\fR
will be concatenated\&.
.sp
When used along with a template file,
\fITEXT\fR
will be appended to the template\*(Aqs
file\-tail
section\&.
.RE
.PP
\fB\-\-eprod\fR \fITEXT\fR
.RS 4
Emits
\fITEXT\fR
every time an enum is encountered in the input files\&.
.RE
.PP
\fB\-\-vhead\fR \fITEXT\fR
.RS 4
Emits
\fITEXT\fR
before iterating over the set of values of an enum\&.
.sp
You can specify this option multiple times, and the
\fITEXT\fR
will be concatenated\&.
.sp
When used along with a template file,
\fITEXT\fR
will be prepended to the template\*(Aqs
value\-header
section\&.
.RE
.PP
\fB\-\-vprod\fR \fITEXT\fR
.RS 4
Emits
\fITEXT\fR
for every value of an enum\&.
.sp
You can specify this option multiple times, and the
\fITEXT\fR
will be concatenated\&.
.sp
When used along with a template file,
\fITEXT\fR
will be appended to the template\*(Aqs
value\-production
section\&.
.RE
.PP
\fB\-\-vtail\fR \fITEXT\fR
.RS 4
Emits
\fITEXT\fR
after iterating over all values of an enum\&.
.sp
You can specify this option multiple times, and the
\fITEXT\fR
will be concatenated\&.
.sp
When used along with a template file,
\fITEXT\fR
will be appended to the template\*(Aqs
value\-tail
section\&.
.RE
.PP
\fB\-\-comments\fR \fITEXT\fR
.RS 4
Template for auto\-generated comments, the default (for C code generations) is
"/* @comment@ */"\&.
.RE
.PP
\fB\-\-template\fR \fIFILE\fR
.RS 4
Read templates from the given file\&. The templates are enclosed in specially\-formatted C comments:
.sp
.if n \{\
.RS 4
.\}
.nf
/*** BEGIN section ***/
/*** END section ***/
.fi
.if n \{\
.RE
.\}
\fIsection\fR
may be
file\-header,
file\-production,
file\-tail,
enumeration\-production,
value\-header,
value\-production,
value\-tail
or
comment\&.
.RE
.PP
\fB\-\-identifier\-prefix\fR \fIPREFIX\fR
.RS 4
Indicates what portion of the enum name should be interpreted as the prefix (eg, the "Gtk" in "GtkDirectionType")\&. Normally this will be figured out automatically, but you may need to override the default if your namespace is capitalized oddly\&.
.RE
.PP
\fB\-\-symbol\-prefix\fR \fIPREFIX\fR
.RS 4
Indicates what prefix should be used to correspond to the identifier prefix in related C function names (eg, the "gtk" in "gtk_direction_type_get_type"\&. Equivalently, this is the lowercase version of the prefix component of the enum value names (eg, the "GTK" in "GTK_DIR_UP"\&. The default value is the identifier prefix, converted to lowercase\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print brief help and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print version and exit\&.
.RE
.PP
\fB\-\-output=FILE\fR
.RS 4
Write output to FILE instead of stdout\&.
.RE
.PP
\fB@RSPFILE\fR
.RS 4
When passed as the sole argument, read and parse the actual arguments from
RSPFILE\&. Useful on systems with a low command\-line length limit\&. For example, Windows has a limit of 8191 characters\&.
.RE
.SH "USING TEMPLATES"
.PP
Instead of passing the various sections of the generated file to the command line of
\fBglib\-mkenums\fR, it\*(Aqs strongly recommended to use a template file, especially for generating C sources\&.
.PP
A C header template file will typically look like this:
.sp
.if n \{\
.RS 4
.\}
.nf
/*** BEGIN file\-header ***/
#pragma once

/* Include the main project header */
#include "project\&.h"

G_BEGIN_DECLS
/*** END file\-header ***/

/*** BEGIN file\-production ***/

/* enumerations from "@basename@" */
/*** END file\-production ***/

/*** BEGIN value\-header ***/
GType @enum_name@_get_type (void) G_GNUC_CONST;
#define @ENUMPREFIX@_TYPE_@ENUMSHORT@ (@enum_name@_get_type ())
/*** END value\-header ***/

/*** BEGIN file\-tail ***/
G_END_DECLS
/*** END file\-tail ***/
.fi
.if n \{\
.RE
.\}
.PP
A C source template file will typically look like this:
.sp
.if n \{\
.RS 4
.\}
.nf
/*** BEGIN file\-header ***/
#include "config\&.h"
#include "enum\-types\&.h"

/*** END file\-header ***/

/*** BEGIN file\-production ***/
/* enumerations from "@basename@" */
/*** END file\-production ***/

/*** BEGIN value\-header ***/
GType
@enum_name@_get_type (void)
{
  static gsize static_g_@type@_type_id;

  if (g_once_init_enter (&static_g_@type@_type_id))
    {
      static const G@Type@Value values[] = {
/*** END value\-header ***/

/*** BEGIN value\-production ***/
            { @VALUENAME@, "@VALUENAME@", "@valuenick@" },
/*** END value\-production ***/

/*** BEGIN value\-tail ***/
            { 0, NULL, NULL }
      };

      GType g_@type@_type_id =
        g_@type@_register_static (g_intern_static_string ("@EnumName@"), values);

      g_once_init_leave (&static_g_@type@_type_id, g_@type@_type_id);
    }
  return static_g_@type@_type_id;
}

/*** END value\-tail ***/
.fi
.if n \{\
.RE
.\}
.PP
Template files are easier to modify and update, and can be used to generate various types of outputs using the same command line or tools during the build\&.
.SH "USING GLIB\-MKENUMS WITH MESON"
.PP
Meson supports generating enumeration types using
\fBglib\-mkenums\fR
out of the box in its "gnome" module\&.
.PP
In your
meson\&.build
file you will typically call the
gnome\&.mkenums_simple()
method to generate idiomatic enumeration types from a list of headers to inspect:
.sp
.if n \{\
.RS 4
.\}
.nf
project_headers = [
  \*(Aqproject\-foo\&.h\*(Aq,
  \*(Aqproject\-bar\&.h\*(Aq,
  \*(Aqproject\-baz\&.h\*(Aq,
]

gnome = import(\*(Aqgnome\*(Aq)
enum_files = gnome\&.mkenums_simple(\*(Aqenum\-types\*(Aq,
  sources: project_headers,
)
.fi
.if n \{\
.RE
.\}
.PP
The
enum_files
variable will contain an array of two elements in the following order:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
a build target for the source file
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
a build target for the header file
.RE
.PP
You should use the returned objects to provide a dependency on every other build target that references the source or header file; for instance, if you are using the source to build a library:
.sp
.if n \{\
.RS 4
.\}
.nf
mainlib = library(\*(Aqproject\*(Aq,
  sources: project_sources + enum_files,
  \&.\&.\&.
)
.fi
.if n \{\
.RE
.\}
.PP
Additionally, if you are including the generated header file inside a build target that depends on the library you just built, you must ensure that the internal dependency includes the generated header as a required source file:
.sp
.if n \{\
.RS 4
.\}
.nf
mainlib_dep = declare_dependency(sources: enum_files[1], link_with: mainlib)
.fi
.if n \{\
.RE
.\}
.PP
You should not include the generated source file as well, otherwise it will be built separately for every target that depends on it, causing build failures\&. To know more about why all this is required, please refer to the
\m[blue]\fBcorresponding Meson FAQ entry\fR\m[]\&\s-2\u[1]\d\s+2\&.
.PP
If you are generating C header and source files that require special templates, you can use
gnome\&.mkenums()
to provide those headers, for instance:
.sp
.if n \{\
.RS 4
.\}
.nf
enum_files = gnome\&.mkenums(\*(Aqenum\-types\*(Aq,
  sources: project_headers,
  h_template: \*(Aqenum\-types\&.h\&.in\*(Aq,
  c_template: \*(Aqenum\-types\&.c\&.in\*(Aq,
  install_header: true,
)
.fi
.if n \{\
.RE
.\}
.PP
For more information, see the
\m[blue]\fBMeson documentation for gnome\&.mkenums()\fR\m[]\&\s-2\u[2]\d\s+2\&.
.SH "USING GLIB\-MKENUMS WITH AUTOTOOLS"
.PP
In order to use
\fBglib\-mkenums\fR
in your project when using Autotools as the build system, you will first need to modify your
configure\&.ac
file to ensure you find the appropriate command using
\fBpkg\-config\fR, similarly as to how you discover the compiler and linker flags for GLib\&.
.sp
.if n \{\
.RS 4
.\}
.nf
PKG_PROG_PKG_CONFIG([0\&.28])

PKG_CHECK_VAR([GLIB_MKENUMS], [glib\-2\&.0], [glib_mkenums])
.fi
.if n \{\
.RE
.\}
.PP
In your
Makefile\&.am
file you will typically use rules like these:
.sp
.if n \{\
.RS 4
.\}
.nf
# A list of headers to inspect
project_headers = \e
        project\-foo\&.h \e
        project\-bar\&.h \e
        project\-baz\&.h

enum\-types\&.h: $(project_headers) enum\-types\&.h\&.in
        $(AM_V_GEN)$(GLIB_MKENUMS) \e
                \-\-template=enum\-types\&.h\&.in \e
                \-\-output=$@ \e
                $(project_headers)

enum\-types\&.c: $(project_headers) enum\-types\&.c\&.in enum\-types\&.h
        $(AM_V_GEN)$(GLIB_MKENUMS) \e
                \-\-template=enum\-types\&.c\&.in \e
                \-\-output=$@ \e
                $(project_headers)

# Build the enum types files before every other target
BUILT_SOURCES += enum\-types\&.h enum\-types\&.c
CLEANFILES += enum\-types\&.h enum\-types\&.c
EXTRA_DIST += enum\-types\&.h\&.in enum\-types\&.c\&.in
.fi
.if n \{\
.RE
.\}
.PP
In the example above, we have a variable called
project_headers
where we reference all header files we want to inspect for generating enumeration GTypes\&. In the
enum\-types\&.h
rule we use
\fBglib\-mkenums\fR
with a template called
enum\-types\&.h\&.in
in order to generate the header file; similarly, in the
enum\-types\&.c
rule we use a template called
enum\-types\&.c\&.in\&.
.SH "SEE ALSO"
.PP
\fBglib-genmarshal\fR(1)
.SH "NOTES"
.IP " 1." 4
corresponding Meson FAQ entry
.RS 4
\%https://mesonbuild.com/FAQ.html#how-do-i-tell-meson-that-my-sources-use-generated-headers
.RE
.IP " 2." 4
Meson
documentation for gnome.mkenums()
.RS 4
\%https://mesonbuild.com/Gnome-module.html#gnomegenmarshal
.RE
