[package]
name = "mplot"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.97"
common = { path = "../common" }
plotpy = "0.4.0"
clap = { version = "4.3.8", features = ["derive"] }
