use clap::Parser;

#[derive(Parser)]
#[command(author = "CHORYNSKI Ewan", about = "Create and save a plot from a json file generated by mprobe")]
pub struct Arguments {
    /// JSON data input file (mprobe output)
    #[clap(required = true)]
    pub inputs: Vec<String>,

    
    /// Output file destination
    #[clap(short, long)]
    pub output: Option<String>,

    /// Don't show the graph and just save it
    #[clap(short, long)]
    pub queit: bool,

    /// Control whether to output only one svg with multiple plot in
    /// it instead of one file per plot in case of multiple input file
    #[clap(short, long)]
    pub single_window: bool,

}
